//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int ID_Test { get; set; }
        public string Name_test { get; set; }
        public string Desc_test { get; set; }
        public string FirstAnswer { get; set; }
        public string SecondAnswer { get; set; }
        public string ThirdAnswer { get; set; }
        public Nullable<int> RA_ID { get; set; }
    
        public virtual RightAnswerTable RightAnswerTable { get; set; }
    }
}
